### PR TITLE
Update nav.component.html

### PR DESCRIPTION
**Pull request by amczuboka**
Added different Landing page logic (commented out) for employer user. Once authentication is done will revisit. Needs to be merged to do issues for creation new sections like "Interviews" and "Applied To"

### CODE REVIEW

**Review by Guillaume-Lachapelle — APPROVED** [review]
Looks good! Will be working on authentication today to finalize this

**Comment by KarinaSandur** [comment]
Looks good to me!

**Review by KarinaSandur — APPROVED** [review]

**Review by IsabelleCzuboka — APPROVED** [review]
i approve, looks okay

**Review by Holyvert — APPROVED** [review]
Looks good

**Review by MillerSty — APPROVED** [review]

**Pull request merged**
