### PR TITLE
Cypress test 86

### PR DESCRIPTION
**Pull request by KarinaSandur**
Pull request for #86 

I added some requirements to test for that Acceptance test. Namely, that when the student is selected for interview, they no longer appear as a candidate for that job post and appear in "Interviews". Also, when a student is unselected for interview, they no longer appear in "Interviews" and, once again, appear as a candidate for that job post.

### CODE REVIEW

**Review by amczuboka — CHANGES_REQUESTED** [review]
My test was unsuccessful. I think it didn't unselect them successfully

**Review by Guillaume-Lachapelle — CHANGES_REQUESTED** [review]
Tested and had the same problem as @amczuboka. Tried adding a longer cy.wait() at more places and it worked. I think the delay depends on each person's computer and network... I didn't commit any changes, but maybe just try to add a bit more cy.wait() and/or maybe longer times (like 3000)

**Review by MillerSty — APPROVED** [review]
I would suggest adding in a post creation and deletion to ensure the test has a post to work one. But besides that the test works and is successfull so I give my approval

**Comment by amczuboka** [comment]
> I would suggest adding in a post creation and deletion to ensure the test has a post to work one. But besides that the test works and is successfull so I give my approval

I agree, if somehow this post from your employer account gets deleted, then this test will fail

**Comment by KarinaSandur** [comment]
Made the requested changes and it works for me. Let me know if you're still having trouble with the page(s) loading @Guillaume-Lachapelle and @amczuboka

**Review by Holyvert — APPROVED** [review]
works find for me

**Review by Guillaume-Lachapelle — APPROVED** [review]
Test successful. Great job!

**Review by IsabelleCzuboka — APPROVED** [review]
Looks good!

**Review by amczuboka — APPROVED** [review]
Looks good on my side

**Pull request merged**
