### PR TITLE
Fix problems from sonarlint

### PR DESCRIPTION
**Pull request by Guillaume-Lachapelle**
Fixed bugs and code smells from sonarqube. Statistics can be seen in the group project report.

### CODE REVIEW

**Review by amczuboka — APPROVED** [review]
Looks great, I tested the branch with actions such as, create, editing and deleting a post. And applying to a post, selecting for interview...

**Review by MillerSty — APPROVED** [review]

**Review by KarinaSandur — APPROVED** [review]
Looks good! Great job!

**Review by IsabelleCzuboka — APPROVED** [review]
Changes look good!

**Review by Holyvert — APPROVED** [review]
looks good

**Pull request merged**
