### PR TITLE
Cypress tests

### LINKED ISSUE #21: Acceptance test(#17):
#17

### LINKED ISSUE #22: Acceptance Test(#6):
#6

### LINKED ISSUE #23: Acceptance Test(#7)
#7

### PR DESCRIPTION
**Pull request by amczuboka**
This pull request englobes all the necessary added files and config files to run Cypress tests. There is also 3 new passing tests related to 3 user stories #7, #6 and #17. You can run individual tests with the command `ng e2e` or run all the tests with `npm run cypress:run`. closes #23 closes #22 closes #21

### CODE REVIEW

**Review by IsabelleCzuboka — APPROVED** [review]
Nice!

**Review by Guillaume-Lachapelle — APPROVED** [review]
Very cool

**Review by MillerSty — APPROVED** [review]
Way to go 👍

**Review by KarinaSandur — APPROVED** [review]
Great job!

**Review by Holyvert — APPROVED** [review]
looks good

**Pull request merged**
