### PR TITLE
Fix cypress test 21, 22, 23

### PR DESCRIPTION
**Pull request by amczuboka**
Fixed little things so that the tests would work including test 88. Will later look into moving the create post test from 88 into 23 so that test 23 creates a post and test 88 deletes the same post. Will only look at that at the end, since will only want to do that when we only want to run all tests together instead of individually

### CODE REVIEW

**Review by Guillaume-Lachapelle — APPROVED** [review]
Tested it and it works. Great job!

**Review by IsabelleCzuboka — APPROVED** [review]
Looks good!

**Review by KarinaSandur — APPROVED** [review]
Looks good to me!

**Review by Holyvert — APPROVED** [review]
looks good

**Review by MillerSty — APPROVED** [review]

**Pull request merged**
