### PR TITLE
Did apply aftermath & apply button visible only if you haven't applied yet

### PR DESCRIPTION
**Pull request by IsabelleCzuboka**
Added Candidates and ID to posting database when registering a new job posting. Sent user id to job posting in candidates attribute as well as sent job posting id to user in appliedto attribute. After applying to a job, the apply button will no longer be there

### CODE REVIEW

**Review by Guillaume-Lachapelle — CHANGES_REQUESTED** [review]
When going into "Applied To" section, the posting cards are unclickable. Also, We could add a "cancel application" button? Maybe in a future task.
Here's an image of the error when clicking on a card:
image
It's because the router tries to redirect to applications/individual
image
I think just changing that line to "['../individual']" should do the job

**Review by Guillaume-Lachapelle — APPROVED** [review]
The new changes look great! Good work!

**Review by MillerSty — APPROVED** [review]
Good job on the changes, looks good

**Review by KarinaSandur — APPROVED** [review]
Looks good! I approve! Although I suspect we may have some merge conflicts with my branch that we will have to look over.

**Review by amczuboka — APPROVED** [review]
Looks Great!

**Review by Holyvert — APPROVED** [review]
I tested it and it works

**Pull request merged**
