### PR TITLE
Candidates section

### PR DESCRIPTION
**Pull request by KarinaSandur**
#52 #49 
This is to merge the 'candidates-section' to Sprint3

### CODE REVIEW

**Review by IsabelleCzuboka — CHANGES_REQUESTED** [review]
I see in the database that you can add the same person twice? Also heads up, we accidently deleted that user while working on the favorite section. 
image

**Comment by Guillaume-Lachapelle** [comment]
@IsabelleCzuboka this is gonna be resolved once we merge this branch with yours (cause you added the implementation to remove the Apply button when someone has already applied).

**Review by Guillaume-Lachapelle — APPROVED** [review]
Looks very nice!

**Review by Holyvert — APPROVED** [review]
I tested it and corrected the issues with @Guillaume-Lachapelle

**Review by MillerSty — APPROVED** [review]

**Review by amczuboka — APPROVED** [review]
Looks great

**Review by IsabelleCzuboka — APPROVED** [review]

**Pull request merged**
