### PR TITLE
Cypress test 83

### LINKED ISSUE #83: Acceptance Test(UserStory #29):
#29

### PR DESCRIPTION
**Pull request by amczuboka**
This cypress test is to check if an employer can edit their profile. closes #83

### CODE REVIEW

**Review by Guillaume-Lachapelle — APPROVED** [review]
Great work! I changed the name of the test to "Enters Credentials of an Employer" (the original said Student). Tested it and works like a charm

**Review by IsabelleCzuboka — APPROVED** [review]
Great work!

**Review by Holyvert — APPROVED** [review]
looks good

**Review by KarinaSandur — APPROVED** [review]
Looks good!

**Comment by KarinaSandur** [comment]
Noticed that the describe said 'Student Logs In' so I changed it.

**Review by MillerSty — APPROVED** [review]
Test succeded on my end

**Pull request merged**
