### PR TITLE
Cypress test Acceptance test (UserStory #5) #81

### LINKED ISSUE #81: Acceptance test (UserStory #5)
User Acceptance Flow:

User logs in.
User clicks on Profile section in nav bar.
User gets redirected to User Profile Page.
User sees there information.
Do for employer and student.

### PR DESCRIPTION
**Pull request by Guillaume-Lachapelle**

### CODE REVIEW

**Review by IsabelleCzuboka — APPROVED** [review]
Looks ready to merge

**Review by Holyvert — APPROVED** [review]
looks good

**Review by KarinaSandur — APPROVED** [review]
I approve!

**Review by amczuboka — APPROVED** [review]
I approve, looks good

**Review by MillerSty — APPROVED** [review]
Test succeeds

**Pull request merged**
