### PR TITLE
Cypress test 114

### LINKED ISSUE #114: Acceptance test(UserStory #112):
User Acceptance Flow:

1. User logs in (does not matter which type)
2. User click on search bar
3. User puts in a keyword such as position, title or company
4. Checks to see that the available posts correspond to search keyword

### PR DESCRIPTION
**Pull request by MillerSty**
2023-04-05_12h44_32
Closes #114

### CODE REVIEW

**Review by amczuboka — APPROVED** [review]
Ran the test on my end and it succeeded!

**Review by IsabelleCzuboka — APPROVED** [review]
Looks good, I think you want to merge into Sprint4 and not Master!

**Review by Guillaume-Lachapelle — APPROVED** [review]
Test successful. Great job!

**Review by Holyvert — APPROVED** [review]
test works fine

**Review by KarinaSandur — APPROVED** [review]
Looks good to me!

**Comment by Holyvert** [comment]
my bad guys

**Pull request merged**
