### PR TITLE
Sprint1

### PR DESCRIPTION
**Pull request by amczuboka**
Merge Sprint 1 into Master branch

### CODE REVIEW

**Review by Holyvert — APPROVED** [review]
looks good

**Review by Guillaume-Lachapelle — APPROVED** [review]
Approved!

**Review by MillerSty — APPROVED** [review]
Looks good

**Review by IsabelleCzuboka — APPROVED** [review]
All looks good to merge sprint 1 into master!

**Review by KarinaSandur — APPROVED** [review]
Looks good to me!

**Pull request merged**
