### PR TITLE
#6 job posts node

### LINKED ISSUE #15: Task: Creation of job-posts database in Firebase (Back-End).
#6

### PR DESCRIPTION
**Pull request by amczuboka**
This ticket was to essentially to set up firebase and create a node for job-posts. Most of the firebase set-up was already done in Firebase basic implmentation #25. Mainly added a function that creates a fake job-posting inside the new job-postings node. Closes #15

### CODE REVIEW

**Review by Guillaume-Lachapelle — APPROVED** [review]
Looks good to me!

**Review by KarinaSandur — APPROVED** [review]
I approve! Looks good!

**Review by MillerSty — APPROVED** [review]

**Review by Holyvert — APPROVED** [review]
good

**Review by IsabelleCzuboka — APPROVED** [review]
Looks good!

**Pull request merged**
