### PR TITLE
#10 landing page

### LINKED ISSUE #10: Task: Landing page of Employers (HTML and CSS) needs to be done (Front-End).
#7

### PR DESCRIPTION
**Pull request by amczuboka**
The nav and footer should be resizable with a toggle menu bar in the nav when double-clicked. The page now has only the necessary info compared to sprint2 branch. Also has the possible added feature of receiving emails if subscribed. 
Closes #10

### CODE REVIEW

**Review by Guillaume-Lachapelle — APPROVED** [review]
Looks great!

**Review by KarinaSandur — APPROVED** [review]
Looks good to me!

**Review by MillerSty — APPROVED** [review]

**Review by Holyvert — APPROVED** [review]
good

**Review by IsabelleCzuboka — APPROVED** [review]
looks clean, I approve

**Pull request merged**
