### PR TITLE
Login component test run

### PR DESCRIPTION
**Pull request by amczuboka**
This is the branch where we added changes to play around with the pages and components. Such as the templates of login, registration, profile and landing pages and how to implement a form in the profile component...

### CODE REVIEW

**Review by MillerSty — APPROVED** [review]

**Review by KarinaSandur — APPROVED** [review]
I approve! Looks good to me!

**Review by IsabelleCzuboka — APPROVED** [review]
All good to me!

**Review by Holyvert — APPROVED** [review]
seems pretty good

**Review by Guillaume-Lachapelle — APPROVED** [review]
Approved

**Pull request merged**
