### PR TITLE
Acceptance test(#48) #88

### PR DESCRIPTION
**Pull request by MillerSty**
Pull request for acceptance test, issue #88 
2023-03-24_16h49_47

### CODE REVIEW

**Review by Guillaume-Lachapelle — APPROVED** [review]
Nice! I added a short delay in the last test to make sure the page is loaded before the test continues. Everything is working.

**Review by IsabelleCzuboka — APPROVED** [review]
Good work!

**Review by amczuboka — APPROVED** [review]
Looks good, the only thing is we have to make sure that if we attach an image when filling up employer form in the test, that we remove the lines that check if the snack bar appears (since that only appears if we don't add an image).

**Review by KarinaSandur — APPROVED** [review]
Good job!

**Review by Holyvert — APPROVED** [review]
looks good

**Pull request merged**
