### PR TITLE
Firebase basic implmentation

### PR DESCRIPTION
**Pull request by MillerSty**
Initial implementation of firebase

### CODE REVIEW

**Review by IsabelleCzuboka — APPROVED** [review]
Looking good!

**Review by Holyvert — APPROVED** [review]
looks good

**Review by KarinaSandur — APPROVED** [review]
Looks great!

**Review by Guillaume-Lachapelle — APPROVED** [review]
Looks good!

**Review by amczuboka — APPROVED** [review]
Looks great!

**Pull request closed without merging**
