### PR TITLE
Edit employer form page

### PR DESCRIPTION
**Pull request by amczuboka**
This pull request adds the edit action for a job post of an employer. The employer gets redirected to the edit-employer-form after clicking "edit" button. Also, when employer clicks edit, the form is auto-filled with all the info. Updated cypress.config.ts file to not record snapshots of failing cypress tests

### CODE REVIEW

**Review by Guillaume-Lachapelle — CHANGES_REQUESTED** [review]
Dropdown for RequiredDocuments, JobLocationType, ApplicationMethod, Deadline, etc...

**Comment by amczuboka** [comment]
@Guillaume-Lachapelle I made the changes for the format of the edit-employer-form

**Review by IsabelleCzuboka — APPROVED** [review]
Looks good!

**Review by Holyvert — APPROVED** [review]
looks goood

**Review by MillerSty — APPROVED** [review]
Good job on the fix, code looks good 👍

**Review by KarinaSandur — APPROVED** [review]
Great work!

**Pull request merged**
