### PR TITLE
#12 add job post to database from employer form

### PR DESCRIPTION
**Pull request by Holyvert**

### CODE REVIEW

**Review by Guillaume-Lachapelle — APPROVED** [review]
Looks great!

**Review by MillerSty — APPROVED** [review]
great work

**Review by KarinaSandur — APPROVED** [review]
Good job! Looks great to me!

**Review by amczuboka — APPROVED** [review]
Looks great

**Review by IsabelleCzuboka — APPROVED** [review]
All good!

**Pull request merged**
