### PR TITLE
Sprint3

### PR DESCRIPTION
**Pull request by Holyvert**
Merging Sprint3 into master for Sprint 3 submission.

### CODE REVIEW

**Review by amczuboka — APPROVED** [review]
Checked out sprint 3 branch and everything looks great!

**Review by IsabelleCzuboka — APPROVED** [review]
Everything looks good to merge!

**Review by Guillaume-Lachapelle — APPROVED** [review]
Looks great! Ready to merge

**Review by MillerSty — APPROVED** [review]
Woo another sprint done! GJ team

**Review by KarinaSandur — APPROVED** [review]
All good!

**Pull request merged**
