### PR TITLE
Student interviews

### LINKED ISSUE #61: Display the info of the job-posting (Employer, Position, Email) that the student has been selected for to the "Interview" page (Back-End).
#59

### PR DESCRIPTION
**Pull request by amczuboka**
This pull request is displaying the posts that the student has been selected for interview by employers. I added manually the node in firebase (SelectedInterviews) and added two job-posts IDs in that node for student am.czuboka@gmail.com. We will reopen the #61 in Sprint 4 to finish the back-end implementation of the select for interview action. closes #61

### CODE REVIEW

**Review by IsabelleCzuboka — APPROVED** [review]
All looks good, we will complete the functionality in sprint 4

**Review by Guillaume-Lachapelle — APPROVED** [review]
Looks good! Will be working on this feature during Sprint4

**Review by KarinaSandur — APPROVED** [review]
Looks good to me!

**Review by MillerSty — APPROVED** [review]

**Review by Holyvert — APPROVED** [review]
looks good

**Pull request merged**
