### PR TITLE
Student interview section

### PR DESCRIPTION
**Pull request by KarinaSandur**
This pull request is to merge student-interview-section onto Sprint3. My student-interview-section branch contains the page where students can see their pending interviews with potential future employers.

### CODE REVIEW

**Review by MillerSty — APPROVED** [review]

**Review by IsabelleCzuboka — APPROVED** [review]
All good!

**Review by amczuboka — CHANGES_REQUESTED** [review]
Good job, love the way it looks! but ideally the cards should be a custom component so we can do an ngFor like we do for postings on the landing page

**Review by Guillaume-Lachapelle — CHANGES_REQUESTED** [review]
I agree with @amczuboka. Also, this page should only be accessible to students.

**Review by Guillaume-Lachapelle — APPROVED** [review]
Nice job! The new component looks great!

**Review by amczuboka — APPROVED** [review]
The components look good!

**Review by Holyvert — APPROVED** [review]

**Pull request merged**
