### PR TITLE
Created cypress test #113

### PR DESCRIPTION
**Pull request by KarinaSandur**
Created pull request for #113

### CODE REVIEW

**Review by MillerSty — APPROVED** [review]
2023-04-07_19h15_13

**Review by Guillaume-Lachapelle — APPROVED** [review]
Test successful! Nice work!

**Review by IsabelleCzuboka — APPROVED** [review]
Good to go!

**Review by amczuboka — APPROVED** [review]
Looks good!

**Review by Holyvert — APPROVED** [review]
looks good works well

**Pull request merged**
