### PR TITLE
Merge AppliedTo into Sprint3

### PR DESCRIPTION
**Pull request by Guillaume-Lachapelle**
Added "AppliedTo" section and setup the component.spec.ts files for testing using "ng test".

### CODE REVIEW

**Review by KarinaSandur — APPROVED** [review]
Looks good!

**Review by IsabelleCzuboka — APPROVED** [review]
Looking good

**Review by amczuboka — APPROVED** [review]
No comment, since this is my branch. closes #57

**Review by Holyvert — APPROVED** [review]
looks good to me

**Review by MillerSty — APPROVED** [review]

**Pull request merged**
