### PR TITLE
Created Cypress test #82

### PR DESCRIPTION
**Pull request by IsabelleCzuboka**
This test verifies that student sees when he is selected for interview and sees that posting is not in interview section if employer unselects for interview. I create a post beforehand and deleted it afterwards.

### CODE REVIEW

**Review by Guillaume-Lachapelle — APPROVED** [review]
Looks good

**Review by KarinaSandur — APPROVED** [review]
Test ran successfully! Good job!

**Review by MillerSty — APPROVED** [review]

**Review by amczuboka — APPROVED** [review]
Runs successfully on my side

**Review by Holyvert — APPROVED** [review]
looks good

**Pull request merged**
