### PR TITLE
Employer interview section

### PR DESCRIPTION
**Pull request by KarinaSandur**
This is a pull request to merge employer-interview-section into Sprint3. This branch that I made contains the page where employers can see their pending interviews with students.

### CODE REVIEW

**Review by MillerSty — APPROVED** [review]

**Review by IsabelleCzuboka — APPROVED** [review]
Good work!

**Review by amczuboka — CHANGES_REQUESTED** [review]
Good job, love the way it looks! but ideally the cards should be a custom component so we can do an ngFor like we do for postings on the landing page

**Review by Guillaume-Lachapelle — APPROVED** [review]
Looks great! Nice job! I agree with @amczuboka's comment.

**Review by Guillaume-Lachapelle — CHANGES_REQUESTED** [review]
Also this page should only be accessible to employers. We should protect it if a student tries to access it.

**Review by Guillaume-Lachapelle — APPROVED** [review]
Nice work! The new component looks great!

**Review by Holyvert — APPROVED** [review]
looks good to me

**Pull request merged**
