### PR TITLE
Sprint4

### PR DESCRIPTION
**Pull request by Guillaume-Lachapelle**
Final merge. Merging Sprint4 into master

### CODE REVIEW

**Review by amczuboka — APPROVED** [review]
Looks great, manually tested the UI by creating, editing, deleting a post, and applying, selecting and interviewing. I also tested the Cypress tests (npm run cypress:run) and all were successful, takes around 10 minutes to run 
Screen Shot 2023-04-18 at 10 30 07 AM

**Review by KarinaSandur — APPROVED** [review]
Looks good! Great work everyone!

**Review by IsabelleCzuboka — APPROVED** [review]
looks ready to merge

**Review by Holyvert — APPROVED** [review]
Looks good

**Review by MillerSty — APPROVED** [review]

**Pull request merged**
