### PR TITLE
Deleting Word doc from Sprint1_with_deletedWordDoc resolves #2

### LINKED ISSUE #2: Wiki page
Create a Wiki page documenting meeting minutes and notes, and remove Word document from project files.

### PR DESCRIPTION
**Pull request by KarinaSandur**
This pull request is to merge Sprint1_with_deletedWordDoc (head branch) with Sprint1 (base branch).

### CODE REVIEW

**Comment by MillerSty** [comment]
Approval from me! Good work

**Comment by Holyvert** [comment]
looks good

**Review by Guillaume-Lachapelle — APPROVED** [review]
Looks good to me!

**Review by MillerSty — APPROVED** [review]
Looks good

**Comment by amczuboka** [comment]
Looks good!

**Review by amczuboka — COMMENTED** [review]
Looks good

**Review by amczuboka — APPROVED** [review]
Looks good, I'll approve it

**Review by IsabelleCzuboka — APPROVED** [review]
Looks good to me!

**Pull request merged**
