### PR TITLE
Student interviews sprint4

### PR DESCRIPTION
**Pull request by Guillaume-Lachapelle**
This is regarding issues #61, #42, and #59

### CODE REVIEW

**Review by KarinaSandur — APPROVED** [review]
Looks amazing! Great job!

**Review by IsabelleCzuboka — APPROVED** [review]
Looks great!

**Review by Holyvert — CHANGES_REQUESTED** [review]
yeah something doesn't work. I applied to a post as a student but as an employer I can't select that student for an interview.
I even created a new job post to see if it works but it still doesn't

image

image

**Comment by Guillaume-Lachapelle** [comment]
@Holyvert the changes were made

**Review by Holyvert — APPROVED** [review]
tested it works good

**Review by MillerSty — APPROVED** [review]

**Review by amczuboka — APPROVED** [review]
Great Work, I tested it out with am.czuboka@gmail.com's account. Also, checked the unselect from interview action. Saw that you add the missing interpolation for the company's name in the interviews section of student.

**Pull request merged**
