### PR TITLE
Cypress test 85

### PR DESCRIPTION
**Pull request by MillerSty**
2023-04-07_19h38_47

### CODE REVIEW

**Review by Guillaume-Lachapelle — APPROVED** [review]
Test successful! Approved

**Review by IsabelleCzuboka — APPROVED** [review]
Looks good!

**Review by KarinaSandur — APPROVED** [review]
I approve! Good work! 

I just changed a log from 'Cypress Tester85 found in "favorites"' to 'Cypress Tester85 found in "Applied to"' and removed some commented out code that we don't need (pertaining to favorites).

**Comment by Holyvert** [comment]
image
i have this problem

**Review by Guillaume-Lachapelle — APPROVED** [review]
The bug is solved. It came from ids that didn't exist in the database in ann-marie's student profile. Now everything is fixed. Approved!

**Review by Holyvert — APPROVED** [review]
looks good

**Review by amczuboka — APPROVED** [review]
Looks great!

**Pull request merged**
